spring:
  # swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/odowan
    username: root
    password: 5460315a

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false # hibernate ?? ???
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

logging:
  level:
    #    org.hibernate.SQL: OFF
    org.hibernate.SQL: DEBUG
#    org.hibernate.SQL: TRACE

# JWT
jwt:
  secret: 6B64DCA4E72F58EDIKU9AAB215FE7ASDKSADASKDEKDA

# Email
mail:
  smtp:
    port: 465
    auth: true
    starttls:
      required: true
      enable: true
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory
      fallback: false
      port: 465

AdminMail:
  id: hyeonusmtp@gmail.com
  password: fmizycipclrfrjsh

#Rediss
redis:
#  host: my-redis # ???
  host: localhost # ??
  port: 6379

